api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "bfcm-wands-discount"
type = "function"
uid = "26990f16-c37a-d701-bc8f-020b1e49e71b345e1da9"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui]
  handle = "b2b-discount-ui"
