api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "free-ovum-wands"
type = "function"
uid = "2d92e604-8164-1aa7-ae96-781b21004da1fec7c0e6"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui]
  handle = "b2b-discount-ui"